'use client';
import { createContext,useContext,useEffect,useState,useRef,useCallback,ReactNode } from 'react';
import { io,Socket } from 'socket.io-client';
import type { Snapshot,SafeUser } from './types';
interface Context {state:Snapshot|null;user:SafeUser|null;connected:boolean;latency:number;loading:boolean;error:string;csrf:string;toast:(m:string)=>void;request:<T=any>(path:string,body?:unknown)=>Promise<T>;login:(body:unknown,demo?:boolean)=>Promise<SafeUser>;logout:()=>Promise<void>;bid:(teamId?:string,amount?:number)=>Promise<void>;refresh:()=>Promise<void>;now:number;}
const AuctionContext=createContext<Context>(null!);
export const useAuction=()=>useContext(AuctionContext);
export function AuctionProvider({children}:{children:ReactNode}){const [state,setState]=useState<Snapshot|null>(null),[user,setUser]=useState<SafeUser|null>(null),[csrf,setCsrf]=useState(''),[connected,setConnected]=useState(false),[latency,setLatency]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[messages,setMessages]=useState<{id:number;text:string}[]>([]),[now,setNow]=useState(Date.now());const socket=useRef<Socket|null>(null),offset=useRef(0),latest=useRef<Snapshot|null>(null),userRef=useRef<SafeUser|null>(null),sequence=useRef(0);userRef.current=user;
 const toast=useCallback((text:string)=>{const id=++sequence.current;setMessages(m=>[...m.slice(-3),{id,text}]);setTimeout(()=>setMessages(m=>m.filter(x=>x.id!==id)),5000);},[]);
 const request=useCallback(async<T=any>(path:string,body?:unknown):Promise<T>=>{const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','x-csrf-token':csrf},body:body===undefined?undefined:JSON.stringify(body)});const data=await res.json();if(!res.ok){if(res.status===401){setUser(null);setCsrf('');}throw new Error(data.error??'Unable to complete the request.');}return data;},[csrf]);
 const accept=useCallback((s:Snapshot)=>{if(latest.current&&s.auction.revision<latest.current.auction.revision)return;const prev=latest.current;latest.current=s;offset.current=s.serverTime-Date.now();setNow(s.serverTime);setState(s);setError('');setConnected(true);const own=userRef.current?.teamId;if(prev&&s.auction.currentBid!==prev.auction.currentBid&&own){if(s.auction.highestBidderId===own)toast('You are the highest bidder');else if(prev.auction.highestBidderId===own)toast('You have been outbid');}if(prev&&s.auction.currentPlayerId!==prev.auction.currentPlayerId)toast('The next player is at the auction table');},[toast]);
 const refresh=useCallback(async()=>{try{const s=await request<Snapshot>('/api/snapshot');accept(s);}catch(e){setError((e as Error).message);setConnected(false);}},[request,accept]);
 useEffect(()=>{fetch('/api/me').then(r=>r.json()).then(d=>{setUser(d.user);setCsrf(d.csrf??'');}).catch(()=>{}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{const client=io({auth:{csrf},transports:['websocket'],reconnection:true});socket.current=client;client.on('connect',()=>{setConnected(false);client.emit('snapshot:request');});client.onAny((event,data)=>{if(data?.auction&&data?.players)accept(data);});client.on('disconnect',()=>setConnected(false));client.on('connect_error',()=>{setConnected(false);setError('Connection lost. Reconnecting to the auction…');});client.on('access:restricted',d=>{setError(d.message);setState(null);latest.current=null;setConnected(false);});const interval=setInterval(()=>{setNow(Date.now()+offset.current);if(client.connected){const started=performance.now();client.timeout(4000).emit('ping:check',(err:unknown)=>{if(!err)setLatency(Math.round(performance.now()-started));});}},1000);void refresh();return()=>{clearInterval(interval);client.disconnect();};},[csrf,accept,refresh]);
 const login=async(body:unknown,demo=false)=>{const d=await request<{user:SafeUser;csrf:string}>(demo?'/api/demo-login':'/api/login',body);setUser(d.user);setCsrf(d.csrf);return d.user;};
 const logout=async()=>{await request('/api/logout',{});setUser(null);setCsrf('');toast('You have signed out');};
 const bid=async(teamId?:string,amount?:number)=>{if(!socket.current?.connected||!state||!connected)throw new Error('Reconnect before placing a bid.');const payload={playerId:state.auction.currentPlayerId,expectedRevision:state.auction.revision,requestId:crypto.randomUUID(),...(teamId?{teamId}:{}),...(amount!==undefined?{amount}:{})};await new Promise<void>((resolve,reject)=>socket.current!.timeout(8000).emit('bid:place',payload,(err:unknown,result:any)=>{if(err){void refresh();reject(new Error('Bid acknowledgement was delayed. Check the current bid before trying again.'));}else if(!result.ok){void refresh();reject(new Error(result.error));}else resolve();}));};
 return <AuctionContext.Provider value={{state,user,connected,latency,loading,error,csrf,toast,request,login,logout,bid,refresh,now}}>{children}<div className="toasts" aria-live="polite">{messages.map(m=><div className="toast" key={m.id}><span className="status-dot"/>{m.text}</div>)}</div></AuctionContext.Provider>;
}
