import { randomUUID } from 'node:crypto';
import type { State, User, Snapshot, Audit, Bid } from '../src/lib/types';
export class DomainError extends Error {constructor(public code:string, message:string, public status=409){super(message);}}
export function ensure(value:unknown,code:string,message:string,status=409):asserts value {if(!value)throw new DomainError(code,message,status);}
export const isAdmin=(u:User)=>u.role==='SUPER_ADMIN'||u.role==='AUCTION_ADMIN';
export function audit(s:State,u:User,action:string,entity:string,before:unknown,after:unknown,ip='internal') {s.audit.push({id:randomUUID(),userId:u.id,action,entity,before:before??null,after:after??null,createdAt:Date.now(),ip});}
export function nextBid(s:State) {const p=s.players.find(p=>p.id===s.auction.currentPlayerId);if(!p)return 0;if(!s.auction.highestBidderId)return p.basePrice;const rule=[...s.settings.increments].sort((a,b)=>b.from-a.from).find(r=>s.auction.currentBid>=r.from)!;return s.auction.currentBid+rule.increment;}
export function snapshot(s:State,onlineTeams:string[]=[]):Snapshot{return {auction:s.auction,players:s.players.filter(p=>p.status!=='ARCHIVED'),teams:s.teams.map(t=>({...t,email:'',phone:'',owner:'',manager:''})),bids:s.bids.slice(-150).map(b=>({...b,userId:'',requestId:''})),results:s.results,settings:s.settings,sets:s.sets,queue:s.queue,nextBid:nextBid(s),serverTime:Date.now(),onlineTeams};}
export function validateTeam(s:State,teamId:string,amount:number) {const team=s.teams.find(t=>t.id===teamId);ensure(team?.enabled,'TEAM_DISABLED','This team is not eligible to bid.');const squad=s.results.filter(r=>r.teamId===teamId&&r.status==='SOLD');ensure(squad.length<team.maxSquad,'SQUAD_FULL','Your squad has reached its limit.');ensure(team.purse>=amount,'INSUFFICIENT_PURSE','Your team does not have enough purse for this bid.');const p=s.players.find(p=>p.id===s.auction.currentPlayerId)!;const overseas=squad.filter(r=>s.players.find(p=>p.id===r.playerId)?.country!=='India').length;ensure(p.country==='India'||overseas<team.maxOverseas,'OVERSEAS_LIMIT','Your overseas player limit has been reached.');const base=Math.min(...s.players.filter(p=>p.status==='UPCOMING').map(p=>p.basePrice),50000);const reserve=Math.max(0,team.minSquad-squad.length-1)*base;ensure(team.purse-amount>=reserve,'SQUAD_RESERVE','Keep enough purse to complete your minimum squad.');return team;}
export interface BidInput {playerId:string;expectedRevision:number;requestId:string;teamId?:string;amount?:number;}
export function placeBid(s:State,u:User,input:BidInput,ip='internal'):Bid {ensure(u.enabled,'FORBIDDEN','Your account is disabled.',403);ensure(isAdmin(u)||u.role==='TEAM_OWNER'||u.role==='TEAM_MANAGER','FORBIDDEN','A team account is required.',403);const teamId=isAdmin(u)?input.teamId:u.teamId;ensure(teamId,'NO_TEAM','Select a team.');if(!isAdmin(u)&&input.teamId)ensure(input.teamId===u.teamId,'FORBIDDEN','You can only bid for your own team.',403);const fingerprint=JSON.stringify({playerId:input.playerId,expectedRevision:input.expectedRevision,teamId,amount:input.amount});const prior=s.requests.find(r=>r.key===input.requestId&&r.userId===u.id);if(prior){ensure(prior.fingerprint===fingerprint,'DUPLICATE_MISMATCH','This request key has already been used.');return s.bids.find(b=>b.id===prior.bidId)!;}const a=s.auction;ensure(!s.settings.maintenance,'MAINTENANCE','The auction is temporarily unavailable.');ensure(a.status==='LIVE'&&a.biddingOpen&&!a.frozen,'BIDDING_CLOSED','Bidding is currently closed.');ensure(!a.timerEndsAt||a.timerEndsAt>Date.now(),'TIMER_EXPIRED','The bidding countdown has ended.');ensure(a.currentPlayerId===input.playerId,'PLAYER_CHANGED','The auction has moved to another player.');ensure(a.revision===input.expectedRevision,'BID_CHANGED','The bid changed. Review the latest price and try again.');ensure(s.players.find(p=>p.id===input.playerId)?.status==='BIDDING','PLAYER_CLOSED','This player is no longer open for bidding.');ensure(a.highestBidderId!==teamId,'ALREADY_LEADING','Your team is already the highest bidder.');const amount=nextBid(s);if(input.amount!==undefined)ensure(input.amount===amount,'INVALID_INCREMENT','Use the next legal bid amount.');validateTeam(s,teamId,amount);for(const b of s.bids)if(b.playerId===input.playerId&&b.status==='ACCEPTED')b.status='SUPERSEDED';const bid:Bid={id:randomUUID(),auctionId:a.id,playerId:input.playerId,teamId,userId:u.id,amount,bidType:isAdmin(u)?'ADMIN_MANUAL':'ONLINE',status:'ACCEPTED',createdAt:Date.now(),requestId:input.requestId};const previous=a.highestBidderId;s.bids.push(bid);s.requests.push({key:input.requestId,userId:u.id,fingerprint,bidId:bid.id});a.currentBid=amount;a.highestBidderId=teamId;if(s.settings.timerEnabled)a.timerEndsAt=Date.now()+s.settings.timerSeconds*1000;a.revision++;audit(s,u,'bid:placed',bid.id,null,bid,ip);s.notifications.push({id:randomUUID(),teamId,message:'You are the highest bidder',createdAt:Date.now()});if(previous)s.notifications.push({id:randomUUID(),teamId:previous,message:'You have been outbid',createdAt:Date.now()});return bid;}
export function openPlayer(s:State,id:string){const p=s.players.find(p=>p.id===id);ensure(p&&p.status!=='SOLD'&&p.status!=='ARCHIVED','PLAYER_UNAVAILABLE','This player cannot be opened.');const old=s.players.find(p=>p.id===s.auction.currentPlayerId);if(old?.status==='BIDDING'){old.status='UPCOMING';if(!s.queue.includes(old.id))s.queue.push(old.id);}for(const bid of s.bids)if(bid.status==='ACCEPTED')bid.status='VOID';p.status='BIDDING';s.queue=s.queue.filter(q=>q!==id);Object.assign(s.auction,{currentPlayerId:id,currentBid:0,highestBidderId:null,biddingOpen:false,timerEndsAt:null,timerRemaining:null});}
export function control(s:State,u:User,action:string,input:{playerId?:string;expectedRevision?:number}={},ip='internal') {ensure(isAdmin(u),'FORBIDDEN','Administrator access is required.',403);const a=s.auction;const before=structuredClone(a);if(input.expectedRevision!==undefined)ensure(input.expectedRevision===a.revision,'STATE_CHANGED','The auction changed. Review the latest state.');const p=s.players.find(p=>p.id===a.currentPlayerId);const sensitive=['sold','unsold','next','skip','previous','reopen','undo','void'];if(sensitive.includes(action))ensure(input.expectedRevision!==undefined,'VERSION_REQUIRED','Refresh the auction state.');
 switch(action){
 case 'start':ensure(a.status!=='COMPLETED','COMPLETED','This auction is complete.');a.status='LIVE';if(!p)openPlayer(s,s.queue[0]);break;
 case 'open':case 'resume':ensure(p?.status==='BIDDING','NO_PLAYER','Open an available player first.');ensure(!a.frozen,'FROZEN','A super admin must unfreeze bidding.');a.status='LIVE';a.biddingOpen=true;if(s.settings.timerEnabled)a.timerEndsAt=Date.now()+(a.timerRemaining??s.settings.timerSeconds*1000);a.timerRemaining=null;break;
 case 'pause':a.status='PAUSED';a.biddingOpen=false;a.timerRemaining=a.timerEndsAt?Math.max(0,a.timerEndsAt-Date.now()):null;a.timerEndsAt=null;break;
 case 'close':a.biddingOpen=false;a.timerEndsAt=null;break;
 case 'sold':{ensure(p?.status==='BIDDING'&&a.highestBidderId&&a.currentBid>0,'NO_WINNER','A valid winning bid is required.');const t=validateTeam(s,a.highestBidderId,a.currentBid);ensure(!s.results.some(r=>r.playerId===p.id&&r.status==='SOLD'),'ALREADY_SOLD','This player is already sold.');t.purse-=a.currentBid;p.status='SOLD';a.biddingOpen=false;a.timerEndsAt=null;const result={id:randomUUID(),playerId:p.id,teamId:t.id,amount:a.currentBid,basePrice:p.basePrice,status:'SOLD' as const,round:a.round,createdAt:Date.now()};s.results.push(result);for(const b of s.bids)if(b.playerId===p.id&&b.status==='ACCEPTED')b.status='WINNING';s.notifications.push({id:randomUUID(),teamId:t.id,message:`Player purchased: ${p.name}`,createdAt:Date.now()});break;}
 case 'unsold':ensure(p?.status==='BIDDING','NO_PLAYER','No player is open.');ensure(!a.highestBidderId,'HAS_BID','Void the active bid before marking this player unsold.');p.status='UNSOLD';s.results.push({id:randomUUID(),playerId:p.id,amount:0,basePrice:p.basePrice,status:'UNSOLD',round:a.round,createdAt:Date.now()});a.biddingOpen=false;a.timerEndsAt=null;break;
 case 'next':case 'skip':case 'previous':{ensure(!a.highestBidderId||p?.status==='SOLD','ACTIVE_BID','Resolve the active bid before changing players.');const id=action==='previous'?[...s.players].filter(x=>x.order<(p?.order??0)&&x.status!=='SOLD'&&x.status!=='ARCHIVED').sort((x,y)=>y.order-x.order)[0]?.id:s.queue[0];ensure(id,'QUEUE_EMPTY','There are no available players in this direction.');openPlayer(s,id);break;}
 case 'reopen':{ensure(u.role==='SUPER_ADMIN','FORBIDDEN','Super admin access is required.',403);ensure(!a.highestBidderId||p?.status==='SOLD','ACTIVE_BID','Resolve the current bid first.');const target=s.players.find(x=>x.id===(input.playerId??a.currentPlayerId));ensure(target?.status==='UNSOLD','INVALID_REOPEN','Undo a sale before reopening a sold player.');a.round++;openPlayer(s,target.id);break;}
 case 'undo':{ensure(u.role==='SUPER_ADMIN','FORBIDDEN','Super admin access is required.',403);const result=[...s.results].reverse().find(r=>r.status==='SOLD'||r.status==='UNSOLD');ensure(result,'NO_ACTION','No completed result can be reversed.');ensure(!a.biddingOpen,'BIDDING_OPEN','Close bidding before reversing a result.');if(result.status==='SOLD'){const t=s.teams.find(t=>t.id===result.teamId)!;t.purse+=result.amount;}result.status='REVERSED';const rp=s.players.find(x=>x.id===result.playerId)!;rp.status='UPCOMING';if(!s.queue.includes(rp.id))s.queue.unshift(rp.id);for(const b of s.bids)if(b.playerId===rp.id&&b.status==='WINNING')b.status='VOID';if(a.currentPlayerId===rp.id)Object.assign(a,{currentPlayerId:null,currentBid:0,highestBidderId:null,timerEndsAt:null});audit(s,u,'sale:compensated',result.id,null,result,ip);break;}
 case 'void':{ensure(u.role==='SUPER_ADMIN','FORBIDDEN','Super admin access is required.',403);ensure(p?.status==='BIDDING'&&a.highestBidderId,'NO_BID','No active bid can be voided.');const b=[...s.bids].reverse().find(b=>b.playerId===p.id&&b.status==='ACCEPTED')!;b.status='VOID';const previous=[...s.bids].reverse().find(x=>x.playerId===p.id&&x.status==='SUPERSEDED'&&x.createdAt<=b.createdAt);if(previous)previous.status='ACCEPTED';a.currentBid=previous?.amount??0;a.highestBidderId=previous?.teamId??null;break;}
 case 'freeze':case 'unfreeze':ensure(u.role==='SUPER_ADMIN','FORBIDDEN','Super admin access is required.',403);a.frozen=action==='freeze';a.biddingOpen=false;a.timerEndsAt=null;break;
 case 'timer-start':case 'timer-reset':ensure(a.biddingOpen,'CLOSED','Open bidding before starting the timer.');s.settings.timerEnabled=true;a.timerEndsAt=Date.now()+s.settings.timerSeconds*1000;break;
 case 'timer-pause':a.timerRemaining=a.timerEndsAt?Math.max(0,a.timerEndsAt-Date.now()):null;a.timerEndsAt=null;break;
 case 'timer-5':case 'timer-10':ensure(a.biddingOpen,'CLOSED','Open bidding before extending the timer.');a.timerEndsAt=Math.max(Date.now(),a.timerEndsAt??Date.now())+(action==='timer-5'?5000:10000);break;
 case 'end':ensure(!a.biddingOpen&&!a.highestBidderId||p?.status==='SOLD','ACTIVE_BID','Resolve current bidding first.');a.status='COMPLETED';a.biddingOpen=false;a.timerEndsAt=null;break;
 default:throw new DomainError('UNKNOWN_ACTION','Unknown auction action.',400);
 }a.revision++;audit(s,u,`auction:${action}`,a.id,before,a,ip);return a;
}
