import { hashSync } from 'bcryptjs';
import { randomBytes } from 'node:crypto';
import type { State, Player, PlayerRole, Role } from '../src/lib/types';

export function createSeed(demo = true, password = randomBytes(18).toString('base64url')): State {
 const teamData = [['Mumbai Warriors','MW','#5b91ff'],['Delhi Strikers','DS','#f36075'],['Chennai Chargers','CC','#ffd34e'],['Rajasthan Kings','RK','#be85ff'],['Bengaluru Blazers','BB','#ff854e'],['Kolkata Knights','KK','#a5a0ff'],['Punjab Panthers','PP','#ff739f'],['Hyderabad Hawks','HH','#52d3bc']];
 const teams = teamData.map(([name,short,color],i)=>({id:`t${i+1}`,name,short,color,logo:'',owner:`${name.split(' ')[0]} Sports Group`,manager:'Team Manager',email:`${short.toLowerCase()}@pavilion.demo`,phone:'',startingPurse:5000000,purse:5000000,minSquad:11,maxSquad:18,maxOverseas:6,enabled:true}));
 const sets = ['Marquee players','Batsmen','Wicketkeepers','All-rounders','Fast bowlers','Spin bowlers'].map((name,i)=>({id:`set${i+1}`,name,order:i}));
 const first = ['Arjun','Rahul','Vikram','Aman','Rohan','Aditya','Karan','Ishaan','Dev','Rishabh','Yash','Siddharth','Aryan','Pranav','Dhruv','Kabir'];
 const last = ['Sharma','Singh','Patel','Verma','Mehta','Rao','Desai','Kapoor','Nair','Joshi'];
 const roles:PlayerRole[] = ['All-rounder','Batsman','Fast bowler','Wicketkeeper','Spin bowler'];
 const players:Player[] = Array.from({length:160},(_,i)=>({id:`P${String(i+1).padStart(3,'0')}`,name:`${first[i%16]} ${last[Math.floor(i/16)]}`,dob:`${1994+i%12}-04-16`,age:32-i%12,country:i%19===18?'Australia':'India',state:['Maharashtra','Delhi','Gujarat','Karnataka','Tamil Nadu'][i%5],city:['Mumbai','New Delhi','Ahmedabad','Bengaluru','Chennai'][i%5],role:roles[i%5],batting:i%4===0?'Left-hand bat':'Right-hand bat',bowling:i%3===0?'Right-arm medium':'Right-arm off break',basePrice:[200000,150000,100000,75000,50000][i%5],category:i<16?'Marquee':i<64?'Capped':'Uncapped',setId:i<16?'set1':`set${[4,2,5,3,6][i%5]}`,order:i,previousTeam:i<16?teams[i%8].name:'—',previousPrice:i<16?150000+i*25000:0,photo:i===0?'/featured-player.png':'',bio:'A composed competitor with a sharp cricketing instinct. An exciting addition to any franchise looking to build a balanced squad.',matches:24+(i*7)%104,runs:450+(i*137)%3200,average:Math.round((24+(i*3)%24)*10)/10,strikeRate:128+(i*7)%42,highestScore:64+(i*13)%71,wickets:12+(i*11)%81,economy:6.4+(i%20)/10,bowlingAverage:19+(i%16),status:'UPCOMING'}));
 players[0]={...players[0],name:'Arjun Sharma',age:26,dob:'2000-04-16',matches:86,runs:2450,average:38.2,strikeRate:148.6,wickets:64,economy:7.2,highestScore:112,status:demo?'BIDDING':'UPCOMING'};
 players[1].name='Rahul Singh';players[2].name='Vikram Patel';players[3].name='Aman Verma';
 const now=Date.now();
 const results:State['results']=[];
 if(demo) for(let i=120;i<144;i++) {const sold=i%6!==0;const team=teams[i%8];const amount=250000+(i%8)*50000;players[i].status=sold?'SOLD':'UNSOLD';if(sold)team.purse-=amount;results.push({id:`r${i}`,playerId:players[i].id,teamId:sold?team.id:undefined,amount:sold?amount:0,basePrice:players[i].basePrice,status:sold?'SOLD':'UNSOLD',round:1,createdAt:now-(144-i)*120000});}
 const users:State['users'] = demo ? ([['admin','Alex Morgan','admin@pavilion.demo','SUPER_ADMIN',undefined],['auctioneer','Sam Taylor','auctioneer@pavilion.demo','AUCTION_ADMIN',undefined],...teams.map((t,i)=>[`owner${i+1}`,`${t.short} Owner`,t.email,'TEAM_OWNER',t.id]),['manager','Mumbai Manager','manager@pavilion.demo','TEAM_MANAGER','t1'],['viewer','Guest Viewer','viewer@pavilion.demo','VIEWER',undefined]] as [string,string,string,Role,string|undefined][]).map(([id,name,email,role,teamId])=>({id,name,email,role,teamId,enabled:true,passwordHash:hashSync(password,12)})) : [{id:'admin',name:'Administrator',email:process.env.BOOTSTRAP_ADMIN_EMAIL!,role:'SUPER_ADMIN',enabled:true,passwordHash:hashSync(password,12)}];
 const bids:State['bids']=demo?[550000,600000,650000,700000,750000,800000,850000].map((amount,i)=>({id:`seed-b${i}`,auctionId:'auction-2027',playerId:'P001',teamId:['t4','t2','t1','t4','t1','t2','t1'][i],userId:'admin',amount,bidType:'ADMIN_MANUAL',status:i===6?'ACCEPTED':'SUPERSEDED',createdAt:now-(7-i)*9000,requestId:`seed-${i}`})):[];
 return {auction:{id:'auction-2027',revision:1,status:demo?'LIVE':'UPCOMING',currentPlayerId:demo?'P001':null,currentBid:demo?850000:0,highestBidderId:demo?'t1':null,biddingOpen:demo,timerEndsAt:null,timerRemaining:null,round:1,frozen:false,demo},players,teams,users,bids,results,audit:[],settings:{name:'Cricket Player Auction',season:2027,date:'2027-02-14T14:00:00+05:30',venue:'Grand Hyatt, Mumbai',currency:'INR',startingPurse:5000000,minSquad:11,maxSquad:18,timerSeconds:30,timerEnabled:false,confirmation:true,publicVisible:true,maintenance:false,rules:'The auctioneer’s decision is final. Each team must build a squad of 11–18 players with a maximum of 6 overseas players. All bids are binding. Teams must reserve the minimum base price for their remaining required squad slots.',categories:['Marquee','Capped','Uncapped'],increments:[{from:0,increment:25000},{from:500000,increment:50000},{from:1000000,increment:100000},{from:2500000,increment:200000}]},sets,queue:players.filter(p=>p.status==='UPCOMING').map(p=>p.id),shortlists:[],sessions:[],notifications:[],requests:[]};
}
