'use client';
import { ReactNode,useEffect } from 'react';
import { X,ArrowUpRight,Shield,UserRound } from 'lucide-react';
import Link from 'next/link';
import { Team,Player } from '@/lib/types';
export function Badge({children,tone='muted'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
export function TeamLogo({team,size=''}:{team?:Team;size?:string}){return <span className={`team-logo ${size}`} style={{'--team':team?.color??'#a8b589'} as React.CSSProperties}>{team?.logo?<img src={team.logo} alt=""/>:<><Shield size={size==='large'?35:23} strokeWidth={1.5}/><b>{team?.short??'PV'}</b></>}</span>;}
export function PlayerAvatar({player,large=false}:{player?:Player;large?:boolean}){return <div className={`player-avatar ${large?'large':''}`}>{player?.photo?<img src={player.photo} alt={player.name}/>:<UserRound size={large?64:25} strokeWidth={1}/>}</div>;}
export function SectionTitle({eyebrow,title,subtitle,action}:{eyebrow?:string;title:string;subtitle?:string;action?:ReactNode}){return <div className="section-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>;}
export function PanelTitle({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}){return <div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>;}
export function TextLink({href,children}:{href:string;children:ReactNode}){return <Link className="text-link" href={href}>{children}<ArrowUpRight size={15}/></Link>;}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><Shield size={32}/><h3>{title}</h3><p>{children}</p></div>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=Array.from(document.querySelectorAll<HTMLElement>('.modal button,.modal input,.modal select,.modal textarea,.modal a[href]')).filter(x=>!(x as HTMLButtonElement).disabled);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);const prev=document.activeElement as HTMLElement;document.body.style.overflow='hidden';setTimeout(()=>document.querySelector<HTMLElement>('.modal button')?.focus(),0);return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow='';prev?.focus();};},[onClose]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-label={title} className="modal"><div className="panel-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</section></div>;}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
